config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'user_application_details/update'
  end
  namespace :public do
    get 'user_application_details/update'
  end
    # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top' #'equipments#index'
    resources :user_applications, only: [:show, :update] do
    member do
        get 'user', to: 'user_applications#user_application_user', as: 'user_application_user'
      end
    end
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :equipments, only: [:index, :new, :create, :show, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    resources :equipments, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :user_application_details
    resources :cart_equipments, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy', to: 'cart_equipments#all_destroy'
      end
    end
    resources :user_applications, only: [:new, :create, :index, :show] do
      collection do
        get 'use_list'
        post 'confirm'
      end
    end
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :cart_equipments, dependent: :destroy
  has_many :user_application_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  enum equipment_status: {available:0, during_use:1, unavailable:2, in_failure:3, under_maintenance:4}

  validates :equipment_name,           presence: true
  validates :management_number,        presence: true
  validates :administrator,            presence: true
  validates :equipment_status,         presence: true

end

app/controllers/admin/equipments_controller.rb
class Admin::EquipmentsController < ApplicationController

 before_action :authenticate_admin!

  def index
    @equipments = Equipment.all.page(params[:page]).per(10)
  end

  def new
    @equipment = Equipment.new
  end

  def show
    @equipment = Equipment.find(params[:id])
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def create
    @equipment = Equipment.new(equipment_params)

    if @equipment.save
      redirect_to admin_equipment_path(@equipment.id)
    else
      render :new 
    end
  end

  def update
    equipment = Equipment.find(params[:id])
    equipment.update(equipment_update_params)

    #equipmentのeditで備品ステータス変更する場合のみ適応
    begin
      user_application = UserApplication.find(params[:user_application_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_equipment_path(equipment)
    return
    end

    #user_applicationのshowで備品ステータスを変更する場合のみ適応
    user_application = UserApplication.find(params[:user_application_id])
    # 全てのステータスが使用中でなくなればapplication_statusを返却確認済みに変更する
    if user_application.equipments.none? { |eq| eq.during_use? }
      user_application.returned!
    end

    redirect_to admin_user_application_path(user_application)
  end


  private

  def equipment_params
    params.require(:equipment).permit(:genre_id, :equipment_name, :management_number,
    :equipment_remarks, :equipment_status, :administrator, :image)
  end

  def equipment_update_params
    params.require(:equipment).permit(:equipment_status)
  end

end

app/helpers/admin/equipments_helper.rb
module Admin::EquipmentsHelper
end

app/helpers/publics/equipments_helper.rb
module Publics::EquipmentsHelper
end

app/views/admin/equipments/edit.html.erb
<div class="container">
  <div class="row">
    <h4>備品編集</h4>
  </div>

  <div class="row mt-3 offset-1">
    <div class="col-8 mx-auto">
      <%= form_with model: @equipment, url: admin_equipment_path, method: :patch do |f| %>

        <div class="form-group">
          <%= f.label :"備品名", class: "col-md-4 col-form-label" %>
          <%= f.text_field :equipment_name %>
        </div>

        <div class="form-group">
          <%= f.label :"管理番号", class: "col-md-4 col-form-label" %>
          <%= f.text_field :management_number %>
        </div>

        <div class="form-group">
          <%= f.label :"備品画像", class: "col-md-4 col-form-label" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="form-group">
          <%= f.label :"ジャンル", class: "col-md-4 col-form-label" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :equipment_genre, style: "width:50%" %>
        </div>

        <div class="form-group">
          <%= f.label :"管理担当者", class: "col-md-4 col-form-label" %>
          <%= f.text_field :administrator %>
        </div>

        <div class="form-group">
            <%= f.label :"備品状態", class: "col-md-4 col-form-label" %>
            <!--使用可能-->
            <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(0) %>
            <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:available], value: Equipment.equipment_statuses.key(0) %>
            <!--使用不可-->
            <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(2) %>
            <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:unavailable], value: Equipment.equipment_statuses.key(2) %>
            <!--故障中-->
            <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(3) %>
            <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:in_failure], value: Equipment.equipment_statuses.key(3) %>
            <!--メンテナンス中-->
            <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(4) %>
            <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:under_maintenance], value: Equipment.equipment_statuses.key(4) %>
        </div>

        <div class="form-group d-flex">
          <%= f.label :"備考", class: "col-md-4 col-form-label" %>
          <%= f.text_area :equipment_remarks, rows: "5" , class: "col-md-4 form-control" %>
        </div>

        <div class="form-group ml-3">
          <%= f.submit "変更を保存", class: "btn-success mx-auto" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/equipments/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-between align-items-center">
    <h4>備品一覧</h4>
    <%= link_to "備品を追加する", new_admin_equipment_path, class: "btn btn-primary btn-sm" %>
  </div>
  
  <div class="row justify-content-center mt-5">
    <div class="col-8">
      <table class="table table-hover table-bordered">
        <thead>
            <tr>
              <th class="text-center">備品ID</th>
              <th>備品名</th>
              <th class="text-center">管理番号</th>
              <th class="text-center">ジャンル</th>
              <th class="text-center">備品ステータス</th>
            </tr>
        </thead>
        <tbody>
            <% @equipments.each do |equipment| %>
            <tr>
              <td class="text-center"><%= equipment.id %></td>
              <td><%= link_to "#{equipment.equipment_name}", admin_equipment_path(equipment.id), class: 'text-dark' %></td>
              <td class="text-center"><%= equipment.management_number %></td>
              <td class="text-center"><%= equipment.genre.equipment_genre %></td>
              <td class="text-center"><%= link_to "#{equipment.equipment_status_i18n}", edit_admin_equipment_path(equipment.id), class: 'text-dark' %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center align-items-center">
        <%= paginate @equipments %>
      </div>
    </div>
  </div>
</div>

app/views/admin/equipments/new.html.erb
<div class="container">
  <div class="row">
    <h4>備品新規登録</h4>
  </div>
  <div class="row mt-3 offset-1">
    <div class="col-8 mx-auto">

        <%= form_with model: @equipment, url: admin_equipments_path do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>

          <div class="form-group">
            <%= f.label :"備品名", class: "col-md-3 col-form-label" %>
            <%= f.text_field :equipment_name %>
          </div>

          <div class="form-group">
            <%= f.label :"管理番号", class: "col-md-3 col-form-label" %>
            <%= f.text_field :management_number %>
          </div>

          <div class="form-group">
            <%= f.label :"備品画像", class: "col-md-3 col-form-label" %>
            <%= f.file_field :image, accept: "image/*" %>
          </div>

          <div class="form-group">
            <%= f.label :"ジャンル", class: "col-md-3 col-form-label" %>
            <%= f.collection_select :genre_id, Genre.all, :id, :equipment_genre %>
          </div>

          <div class="form-group">
            <%= f.label :"管理担当者", class: "col-md-3 col-form-label" %>
            <%= f.text_field :administrator %>
          </div>

          <div class="form-group">
            <%= f.label :"備品状態", class: "col-md-3 col-form-label" %>
              <!--使用可能-->
              <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(0) %>
              <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:available], value: Equipment.equipment_statuses.key(0) %>
              <!--使用不可-->
              <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(2) %>
              <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:unavailable], value: Equipment.equipment_statuses.key(2) %>
              <!--故障中-->
              <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(3) %>
              <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:in_failure], value: Equipment.equipment_statuses.key(3) %>
              <!--メンテナンス中-->
              <%= f.radio_button :equipment_status, Equipment.equipment_statuses.key(4) %>
              <%= f.label :equipment_status, Equipment.equipment_statuses_i18n[:under_maintenance], value: Equipment.equipment_statuses.key(4) %>
          </div>

          <div class="form-group d-flex">
            <%= f.label :"備考", class: "col-md-3 col-form-label" %>
            <%= f.text_area :equipment_remarks, rows: '5', class: "col-md-4 form-control" %>
          </div>

          <div class="form-group ml-3">
            <%= f.submit "新規登録", class: "btn-success mx-auto" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/equipments/show.html.erb
<div class="container">
  <div class="row">
    <h4>備品詳細</h4>
  </div>

  <div class="row offset-2 mt-5">
    <div class="col-md-4">
      <% if @equipment.image.attached? %>
        <%= image_tag @equipment.image, class: "show-img" %>
      <% else %>
        <%= image_tag 'no_image', class: "show-img" %>
      <% end %>
      <div class="d-flex justify-content-center mt-5">
        <p class="mr-2">管理担当者 :</p>
        <div class="ml-3">
          <p><%= @equipment.administrator %></p>
        </div>
      </div>
    </div>
    <div class="col-md-4 offset-2">
      <table class="table">
        <tr><td>備品名</td><td><%= @equipment.equipment_name %></td></tr></br>
        <tr><td>管理番号</td><td><%= @equipment.management_number %></td></tr>
        <tr><td>ジャンル</td><td><%= @equipment.genre.equipment_genre %></td></tr>
        <tr><td>備品ステータス</td><td><%= @equipment.equipment_status_i18n %></td></tr>
        <tr><td>備考</td><td><%= @equipment.equipment_remarks %></td></tr>
      </table>
    </div>
  </div>

  <div class="row pt-2 pl-4">

    <div class="col-md-3 offset-3">
      <%= link_to "使用履歴", admin_root_path(equipment_id: @equipment.id), class: "btn btn-warning btn-sm" %>
    </div>

    <div class="col-md-3 offset-2">
      <%= link_to '編集する', edit_admin_equipment_path(params[:id]),class:'btn btn-success btn-sm' %>
    </div>
  </div>
</div>