config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'user_application_details/update'
  end
  namespace :public do
    get 'user_application_details/update'
  end
    # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top' #'equipments#index'
    resources :user_applications, only: [:show, :update] do
    member do
        get 'user', to: 'user_applications#user_application_user', as: 'user_application_user'
      end
    end
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :equipments, only: [:index, :new, :create, :show, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    resources :equipments, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :user_application_details
    resources :cart_equipments, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy', to: 'cart_equipments#all_destroy'
      end
    end
    resources :user_applications, only: [:new, :create, :index, :show] do
      collection do
        get 'use_list'
        post 'confirm'
      end
    end
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_equipment.rb
class CartEquipment < ApplicationRecord
  belongs_to :user
  belongs_to :equipment
  
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :cart_equipments, dependent: :destroy
  has_many :user_application_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  enum equipment_status: {available:0, during_use:1, unavailable:2, in_failure:3, under_maintenance:4}

  validates :equipment_name,           presence: true
  validates :management_number,        presence: true
  validates :administrator,            presence: true
  validates :equipment_status,         presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :equipments
  
  validates :equipment_genre, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_applications, dependent: :destroy
  has_many :cart_equipments, dependent: :destroy
  
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :employee_number,         presence: true
  validates :affiliation,             presence: true
  validates :phone_number,            presence: true
  
end

app/models/user_application.rb
class UserApplication < ApplicationRecord
  has_many :user_application_details, dependent: :destroy
  has_many :equipments, through: :user_application_details
  belongs_to :user

  enum application_status: {applying:0, during_use:1, return_pending:2, returned:3}

  validates :objective,               presence: true
  validates :start_date,              presence: true
  validates :end_date,                presence: true
  validates :return_date,             presence: true
  validates :location,                presence: true
  validates :application_status,      presence: true
  
end

app/models/user_application_detail.rb
class UserApplicationDetail < ApplicationRecord
  belongs_to :user_application
  belongs_to :equipment
  
  has_one_attached :image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

before_action :authenticate_admin!

  def index
    @genres = Genre.all.page(params[:page]).per(10)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
     @genre = Genre.find(params[:id])
  end

  def update
     @genre = Genre.find(params[:id])
     @genre.update(genre_params)
     redirect_to admin_genres_path(@genre.id)
  end

private
  def genre_params
    params.require(:genre).permit(:equipment_genre)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    application_status = params[:application_status]
    if params[:application_status].present?
      @user_applications = UserApplication.where(application_status: application_status).order(created_at: :desc).page(params[:page]).per(10)
    elsif !params[:equipment_id].present?
      @user_applications = UserApplication.all.order(created_at: :desc).page(params[:page]).per(10)
    else
      @user_applications = UserApplication.joins(:equipments).where(equipments: {id: params[:equipment_id]}).order(created_at: :desc).page(params[:page]).per(10)
    end
    session[:previous_url] = request.original_url
  end

  private

  def user_application_params
    params.require(:user_application).permit(:objective,:start_date,:end_date,:location,:application_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  
  protected
  
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users =  User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted,:email,:last_name, :first_name,
    :last_name_kana, :first_name_kana, :employee_number, :affiliation, :phone_number)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!,except:[:about,:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/helpers/admin/applications_helper.rb
module Admin::ApplicationsHelper
end

app/helpers/admin/equipments_helper.rb
module Admin::EquipmentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/equipments_helper.rb
module Publics::EquipmentsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/admin/genres/_genresearch.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td>
          <%= link_to genre.equipment_genre, root_path(genre_id: genre.id), class: 'text-dark' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
  <h4>ジャンル編集</h4>
  </div>
  <div class="row">
   <div class="col-5">
    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
    <table class= "table">
     <tr>
      <td>ジャンル名</td>
       <td><%= f.text_field :equipment_genre %></td>
       <td><%= f.submit '変更を保存', class: "btn-success btn-sm mx-auto" %></td>
     </tr>
    </table>
    <% end %>
   </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <h4>ジャンル一覧・追加</h4>
  </div>
  
  <div class="row justify-content-center mt-5">
   <div class="col-5">
    <%= form_with model: @genre, url: admin_genres_path do |f| %>
     <table class="table table-borderless">
      <tr>
       <th>ジャンル名</th>
       <td><%= f.text_field :equipment_genre %></td>
       <td><%= f.submit '新規登録', class: "btn-primary btn-sm" %></td>
      </tr>
     </table>
    <% end %>
   </div>
 </div>

   <div class="row justify-content-center">
    <div class="col-5">
     <table class="table table-borderless">
      <thead>
      <tr class="text-center">
       <th>ジャンル</th>
      </tr>
    </thead>
      <% @genres.each do |genre| %>
      <tr class="text-center">
       <td><%= genre.equipment_genre %></td>
       <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm mx-auto" %></td>
      </tr>
      <% end %>
    </table>
    <div class="d-flex justify-content-center align-items-center">
      <%= paginate @genres %>
    </div>
    </div>
   </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class='container px-sm-0'>
  <div class='row justify-content-between align-items-center'>
    <div class="col-4">
      <h4>TOPページ(申請履歴一覧)</h4>
    </div>
    <div class="col-4 d-flex justify-content-between">
      <div>
        <%= link_to "使用中", admin_root_path(application_status: "during_use"), class: "btn btn-danger  btn-sm" %>
      </div>
      <div>
        <%= link_to "申請中", admin_root_path(application_status: "applying"), class: "btn btn-primary btn-sm" %>
      </div>
      <div>
        <%= link_to "返却確認待ち", admin_root_path(application_status: "return_pending"), class: "btn btn-warning btn-sm" %>
      </div>
      <div>
        <%= link_to "返却確認済み", admin_root_path(application_status: "returned"), class: "btn btn-success btn-sm" %>
      </div>
    </div>
  </div>

  <div class='row justify-content-center mt-5'>
    <div class="col-9">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>申請日時</th>
            <th>申請者</th>
            <th>目的</th>
            <th class="text-center">申請ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @user_applications.each do |user_application| %>
          <tr>
            <td>
              <%= link_to admin_user_application_path(user_application.id, url: request.original_url), class: 'text-dark' do %>
                <%=  user_application.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M:%S') %>
              <% end %>
            </td>
            <td>
              <%= link_to user_application_user_admin_user_application_path(user_application.user_id) ,class: 'text-dark' do %>
                <%= user_application.user.last_name + " " + user_application.user.first_name %>
              <% end %>
            </td>
            <td><%= user_application.objective %></td>
            <td class="text-center">
              <%= link_to admin_user_application_path(user_application.id, url: request.original_url), class: 'text-dark' do %>
              <%= user_application.application_status_i18n %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center align-items-center">
        <%= paginate @user_applications %>
      </div>
    </div>
  </div>
</div>