config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'user_application_details/update'
  end
  namespace :public do
    get 'user_application_details/update'
  end
    # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top' #'equipments#index'
    resources :user_applications, only: [:show, :update] do
    member do
        get 'user', to: 'user_applications#user_application_user', as: 'user_application_user'
      end
    end
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :equipments, only: [:index, :new, :create, :show, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    resources :equipments, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :user_application_details
    resources :cart_equipments, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy', to: 'cart_equipments#all_destroy'
      end
    end
    resources :user_applications, only: [:new, :create, :index, :show] do
      collection do
        get 'use_list'
        post 'confirm'
      end
    end
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_applications, dependent: :destroy
  has_many :cart_equipments, dependent: :destroy
  
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :employee_number,         presence: true
  validates :affiliation,             presence: true
  validates :phone_number,            presence: true
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users =  User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted,:email,:last_name, :first_name,
    :last_name_kana, :first_name_kana, :employee_number, :affiliation, :phone_number)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class='container' >
  <div class='row'>
    <h4><%= @user.last_name %><%= @user.first_name %>さんの会員情報編集</h4>
  </div>
  <div class="row mt-5 offset-1">
    <div class='col-8 mx-auto'>
    <%= form_with model: @user ,url:admin_user_path, method: :patch, local: true do |f| %>
      <div class="form-group d-flex">
        <%= f.label :"氏名", class: "col-md-4 col-form-label" %>
        <%= f.text_field :last_name, class: "col-sm-4 form-control", autofocus: true %>
        <%= f.text_field :first_name, class: "col-sm-4 offset-1 form-control" %>
      </div>

      <div class="form-group d-flex">
        <%= f.label :"フリガナ", class: "col-md-4 col-form-label" %>
        <%= f.text_field :last_name_kana, class: "col-sm-4 form-control" %>
        <%= f.text_field :first_name_kana, class: "col-sm-4 offset-1 form-control"  %>
      </div>

      <div class="form-group d-flex">
        <%= f.label :"所属", class: "col-md-4 col-form-label" %>
        <%= f.text_field :affiliation, class: "col-sm-4 form-control" %>
      </div>

      <div class="form-group d-flex">
        <%= f.label :"社員番号", class: "col-md-4 col-form-label" %>
        <%= f.text_field :employee_number, class: "col-sm-4 form-control" %>
      </div>

      <div class="form-group d-flex">
        <%= f.label :"電話番号", class: "col-md-4 col-form-label" %>
        <%= f.text_field :phone_number, class: "col-sm-4 form-control" %>
      </div>

      <div class="form-group d-flex">
        <%= f.label :"メールアドレス", class: "col-md-4 col-form-label" %>
        <%= f.text_field :email, class: "col-sm-4 form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"会員ステータス", class: "col-md-4 col-form-label" %>
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, '有効' %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted , '無効' %>
      </div>

      <div class="form-group ml-3">
        <%= f.submit '変更を保存',class:'btn btn-success' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class='container'>
  <div class='row '>
    <h4>会員一覧</h4>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-8">
      <table class="table table-hover table-bordered">
        <thead>
          <tr class="text-center">
            <th>会員ID</th>
            <th>氏名</th>
            <th>社員番号</th>
            <th>メールアドレス</th>
            <th>会員ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr class="text-center">
            <td><%= user.id %></td>
            <td><%= link_to admin_user_path(user.id) ,class: 'text-dark' do %>
            <%= user.last_name + " " + user.first_name %>
            <% end %>
            </td>
            <td><%= user.employee_number %></td>
            <td><%= user.email %></td>
            <td><% if user.is_deleted == true %>
            <div class= "text-secondary">無効</div>
            <% else %>
            <div class= "text-success">有効</div>
            <% end %>
            </td>
          </tr>
        <% end %>
        <%= paginate @users %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center align-items-center">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <h4><%= @user.last_name %><%= @user.first_name %>さんの会員詳細</h4>
  </div>
  <div class="row d-flex align-items-center text-center mt-3 offset-1">
    <h5>登録情報</h5>
    <%= link_to "編集する", edit_admin_user_path(params[:id]),class:"btn btn-success ml-4 mb-2" %>
  </div>
  <div class="row mt-4 offset-1">
    <table class="table table-bordered" style="width: 500px;">
      <tr>
        <th>会員ID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @user.last_name %> <%= @user.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @user.last_name_kana %> <%= @user.first_name_kana %></td>
      </tr>
      <tr>
        <th>所属</th>
        <td><%= @user.affiliation %></td>
      </tr>
      <tr>
        <th>社員番号</th>
        <td><%= @user.employee_number %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @user.phone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <% if @user.is_deleted == true %>
          <td class= text-secondary>無効</td>
        <% else %>
          <td class= text-success>有効</td>
        <% end %>
      </tr>
    </table>
  </div>
</div>