config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'user_application_details/update'
  end
  namespace :public do
    get 'user_application_details/update'
  end
    # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top' #'equipments#index'
    resources :user_applications, only: [:show, :update] do
    member do
        get 'user', to: 'user_applications#user_application_user', as: 'user_application_user'
      end
    end
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :equipments, only: [:index, :new, :create, :show, :edit, :update]
  end

  scope module: :public do
    root to: 'homes#top'
    resources :equipments, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :user_application_details
    resources :cart_equipments, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'all_destroy', to: 'cart_equipments#all_destroy'
      end
    end
    resources :user_applications, only: [:new, :create, :index, :show] do
      collection do
        get 'use_list'
        post 'confirm'
      end
    end
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_equipment.rb
class CartEquipment < ApplicationRecord
  belongs_to :user
  belongs_to :equipment
  
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :cart_equipments, dependent: :destroy
  has_many :user_application_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  enum equipment_status: {available:0, during_use:1, unavailable:2, in_failure:3, under_maintenance:4}

  validates :equipment_name,           presence: true
  validates :management_number,        presence: true
  validates :administrator,            presence: true
  validates :equipment_status,         presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :equipments
  
  validates :equipment_genre, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_applications, dependent: :destroy
  has_many :cart_equipments, dependent: :destroy
  
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :employee_number,         presence: true
  validates :affiliation,             presence: true
  validates :phone_number,            presence: true
  
end

app/models/user_application.rb
class UserApplication < ApplicationRecord
  has_many :user_application_details, dependent: :destroy
  has_many :equipments, through: :user_application_details
  belongs_to :user

  enum application_status: {applying:0, during_use:1, return_pending:2, returned:3}

  validates :objective,               presence: true
  validates :start_date,              presence: true
  validates :end_date,                presence: true
  validates :return_date,             presence: true
  validates :location,                presence: true
  validates :application_status,      presence: true
  
end

app/models/user_application_detail.rb
class UserApplicationDetail < ApplicationRecord
  belongs_to :user_application
  belongs_to :equipment
  
  has_one_attached :image
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    application_status = params[:application_status]
    if params[:application_status].present?
      @user_applications = UserApplication.where(application_status: application_status).order(created_at: :desc).page(params[:page]).per(10)
    elsif !params[:equipment_id].present?
      @user_applications = UserApplication.all.order(created_at: :desc).page(params[:page]).per(10)
    else
      @user_applications = UserApplication.joins(:equipments).where(equipments: {id: params[:equipment_id]}).order(created_at: :desc).page(params[:page]).per(10)
    end
    session[:previous_url] = request.original_url
  end

  private

  def user_application_params
    params.require(:user_application).permit(:objective,:start_date,:end_date,:location,:application_status)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users =  User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted,:email,:last_name, :first_name,
    :last_name_kana, :first_name_kana, :employee_number, :affiliation, :phone_number)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!,except:[:about,:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/helpers/admin/applications_helper.rb
module Admin::ApplicationsHelper
end

app/helpers/admin/equipments_helper.rb
module Admin::EquipmentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/equipments_helper.rb
module Publics::EquipmentsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="row d-flex align-items-end m-3 justify-content-between">
  <div class="col-4">
  <% if user_signed_in? %>
    <h5>ログイン：<%= current_user.last_name %><%= current_user.first_name %></h5>
  <% end %>
  </div>
  <div class="d-flex">
    <% if admin_signed_in? %>
      <%= render 'layouts/headeradmin' %>
    <% elsif user_signed_in? %>
      <%= render 'layouts/headeruser' %>
    <% else %>
      <%= render 'layouts/headersignin' %>
    <% end %>
    </div>
</div>
<hr class="my-4" color="#999999">

app/views/layouts/_headeradmin.html.erb
<div class="nav-item">
  <%= link_to "TOPページ", admin_root_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "備品一覧", admin_equipments_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "会員一覧", admin_users_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-lg btn-outline-dark" %>
</div>

app/views/layouts/_headersignin.html.erb
<div class="nav-item">
  <%= link_to "新規登録", new_user_registration_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-outline-dark" %>
</div>

app/views/layouts/_headeruser.html.erb
<div class="nav-item">
  <%= link_to "TOPページ", root_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "マイページ", user_path(current_user), class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "使用一覧", use_list_user_applications_path, class: "btn btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "カート", cart_equipments_path, class: "btn  btn-lg btn-outline-dark" %>
</div>
<div class="nav-item">
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-lg btn-outline-dark" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    <!--画像クリック時にポップアップ表示-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>